### PR TITLE
MInor Changes

### PR DESCRIPTION
**Pull request by arturobernalg**
* Simplify expressions
* Use java array style
* Replace Explicit with <>

### CODE REVIEW

**Comment by garydgregory** [comment]
@arturobernalg 
May you please rebase on master?
TY.

**Comment by arturobernalg** [comment]
> @arturobernalg
> May you please rebase on master?
> TY.

HI @garydgregory 
Done

**Comment by garydgregory** [comment]
@arturobernalg May you please rebase on master?

**Comment by arturobernalg** [comment]
> @arturobernalg May you please rebase on master?

Done.
TY

**Pull request merged**
