### PR TITLE
Update arguments.c to support Java 11 --enable-preview

### PR DESCRIPTION
**Pull request by mads1980**
See https://issues.apache.org/jira/browse/DAEMON-419

### CODE REVIEW

**Comment by garydgregory** [comment]
@mads1980 
May you please update `help.c` to match?

**Comment by mads1980** [comment]
Done

*Manuel Dominguez Sarmiento*

**Comment by garydgregory** [comment]
Hm, the comments and help should read that the `--enable-preview` is for Java 11 and above, not just for Java 12.
What about the `--release` option like `--release 12`?

**Comment by mads1980** [comment]
You are right. I just tested on Java 11.0.7 and --enable-preview is 
already an option. I have commited the changes to the comments.
Regarding --release I believe that only applies to the compiler (javac), 
not the JVM

*Manuel Dominguez Sarmiento*

**Comment by garydgregory** [comment]
Are there other Java 11, 12, 13, 14, 15, 16 standard flags we should add?

**Comment by mads1980** [comment]
Not that I am aware of.

**Pull request merged**
